import { useEffect } from "react";
import type { NextPage } from "next";
import { useDispatch, useSelector } from "react-redux";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getEmployees } from "@/actions/employee.actions";

const inter = Inter({ subsets: ["latin"] });

interface IEmployees {}

const Employees: NextPage<IEmployees> = () => {
  const dispatch = useDispatch();
  const employees = useSelector((state: any) => state?.employee?.employees);
  console.log("🚀 ~ file: list.tsx:16 ~ Employees ~ employees:", employees);
  console.log("Employees ~ employees:", employees?.data?.countyList);

  useEffect(() => {
    if (typeof window !== "undefined") {
      // This will prevent the dispatch from running during SSR
      dispatch(getEmployees());
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        Employee
        {/* <div> */}
        {employees?.data?.countyList?.map((country: any, i: number) => {
          return <div key={i}>{country}</div>;
        })}
        {/* </div> */}
      </main>
    </>
  );
};

export default Employees;
