const ACTION_HEADER = "EMPLOYEE/";

export const GET_EMPLOYEES = ACTION_HEADER + "GET_EMPLOYEES";
export const GET_EMPLOYEES_SUCCESS = ACTION_HEADER + "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAIL = ACTION_HEADER + "GET_EMPLOYEES_FAIL";
